version: "3.9"

services:
  backend:
    build:
      context: ./vetgroup_backend
    ports:
      - "1337:1337"
    env_file:
      - ./vetgroup_backend/.env
    environment:
      NODE_ENV: production
      STRAPI_ADMIN_HOST: 0.0.0.0
      # optionally, if you set it:
      # STRAPI_ADMIN_URL: https://vetgroup.am/admin
    volumes:
      # Only persist data, not the whole app
      - ./vetgroup_backend/.tmp:/srv/app/.tmp
      - ./vetgroup_backend/public/uploads:/srv/app/public/uploads



  frontend:
    build:
      context: ./vetgroup
    command: npm run dev -- --hostname 0.0.0.0
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      NODE_ENV: development
      NEXT_TELEMETRY_DISABLED: "1"
      NEXT_PUBLIC_API_URL: http://backend:1337
    volumes:
      - ./vetgroup:/app
      - vetgroup_node_modules:/app/node_modules

volumes:
  vetgroup_node_modules:
  vetgroup_backend_node_modules:
